"""Updated the primary keys for all the tables

Revision ID: 146a5c430ff2
Revises: 1e175ec95b72
Create Date: 2024-07-15 14:29:18.972122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146a5c430ff2'
down_revision: Union[str, None] = '1e175ec95b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
