"""Added a store mapper for the store sections model

Revision ID: 1e175ec95b72
Revises: 239f0780e6bc
Create Date: 2024-07-15 14:18:37.225878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e175ec95b72'
down_revision: Union[str, None] = '239f0780e6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
