"""Added a store mapper for the employees model

Revision ID: 239f0780e6bc
Revises: a358b565e1e6
Create Date: 2024-07-15 14:17:20.356881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239f0780e6bc'
down_revision: Union[str, None] = 'a358b565e1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
