"""Added a region mapper for the employees model

Revision ID: a358b565e1e6
Revises: e7e0f2bbdb4a
Create Date: 2024-07-15 14:15:11.116903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a358b565e1e6'
down_revision: Union[str, None] = 'e7e0f2bbdb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
