"""Added a region mapper for the stores model

Revision ID: e7e0f2bbdb4a
Revises: c3e450304613
Create Date: 2024-07-15 14:10:50.643059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e0f2bbdb4a'
down_revision: Union[str, None] = 'c3e450304613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
