"""Reduced the size of the employee model

Revision ID: f2ba17dc9eb0
Revises: d5267b53544f
Create Date: 2024-07-22 14:46:42.882860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2ba17dc9eb0'
down_revision: Union[str, None] = 'd5267b53544f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employee_phone_number')
    op.drop_column('employees', 'is_active')
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('employee_phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
